name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: Package Extension
        run: npm run package

      - name: Publish to VS Code Marketplace
        if: success() && startsWith(github.ref, 'refs/tags/') && env.VSCE_PAT != ''
        run: npx vsce publish --packagePath *.vsix

      - name: Publish to OpenVSX
        if: success() && startsWith(github.ref, 'refs/tags/') && env.OVSX_PAT != ''
        run: npx ovsx publish *.vsix

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: "*.vsix"
